title: "We The People: Unscripted"
description: "Cutting through the noise. Talking about what really matters."
url: "https://agreeable-rock-06dde0010.6.azurestaticapps.net"

author:
  name: "Marcia Tucker"
  location: "United States"

theme: "minimal-mistakes-jekyll"

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author: Marcia Tucker
      read_time: true
      comments: false
      share: true
      related: true

show_excerpts: true
